#!/usr/bin/env node

'use strict';

/**
 * Simple User Enrollment Script (Without CA)
 * 
 * This script creates a wallet identity using the cryptogen-generated certificates
 * from the test-network, bypassing the need for fabric-ca-client.
 */

const { Wallets } = require('fabric-network');
const fs = require('fs');
const path = require('path');

async function main() {
    try {
        console.log('\n========================================');
        console.log('  Enrolling User Without CA');
        console.log('========================================\n');

        // Wallet path
        const walletPath = path.join(__dirname, 'wallet');
        const wallet = await Wallets.newFileSystemWallet(walletPath);
        
        console.log(`Wallet path: ${walletPath}`);

        // Check if user already exists
        const userIdentity = await wallet.get('appUser');
        if (userIdentity) {
            console.log('✓ User "appUser" already exists in wallet');
            return;
        }

        console.log('Creating identity for "appUser"...');

        // Path to user certificates (generated by cryptogen)
        const credPath = path.join(
            __dirname,
            '..',
            '..',
            'fabric-samples',
            'test-network',
            'organizations',
            'peerOrganizations',
            'org1.example.com',
            'users',
            'User1@org1.example.com'
        );

        const certificate = fs.readFileSync(
            path.join(credPath, 'msp', 'signcerts', 'User1@org1.example.com-cert.pem')
        ).toString();
        
        const privateKeyPath = path.join(credPath, 'msp', 'keystore');
        const privateKeyFiles = fs.readdirSync(privateKeyPath);
        const privateKey = fs.readFileSync(
            path.join(privateKeyPath, privateKeyFiles[0])
        ).toString();

        // Create X.509 identity
        const x509Identity = {
            credentials: {
                certificate: certificate,
                privateKey: privateKey,
            },
            mspId: 'Org1MSP',
            type: 'X.509',
        };

        // Import identity into wallet
        await wallet.put('appUser', x509Identity);
        
        console.log('✓ Successfully created identity for "appUser"');
        console.log('✓ Identity stored in wallet\n');
        
        console.log('========================================');
        console.log('  Enrollment Complete!');
        console.log('========================================\n');

    } catch (error) {
        console.error(`\n✗ Failed to enroll user: ${error}`);
        console.error(error.stack);
        process.exit(1);
    }
}

main();
